### ISSUE TITLE
Docker container stopped working after yesterday's update

### ISSUE THREAD

**Issue by Dinth** [lunik1/docker-tt-rss#3]
Hi. Ive been running lunik1/tt-rss for months without any issues, but after yesterday's update it stopped working.
When im trying to open ttrss in my browser im getting the following error:
```
Exception while creating PDO object:SQLSTATE[08006] [7] could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```
The container is set to us PGSQL database through env variables
![Screenshot from 2021-02-26 08-16-28](https://user-images.githubusercontent.com/313674/109274089-fdeb6280-780a-11eb-851a-a643d16dffea.png)

The database is up and running i can connect to it using psql -d ttrss -h 10.10.1.12 -W -U ttrss

**Comment by rosti76** [comment]
its the same issue, convert config.php to new format and it works again.

https://community.tt-rss.org/t/rip-config-php-hello-classes-config-php/4337

**Comment by Biepa** [comment]
For other users coming here.
I just moved the config.php to something like config.php.backup.
Prefix all Docker environment variable names with "TTRSS_" like this: DB_TYPE -> TTRSS_DB_TYPE
(example here: https://git.tt-rss.org/fox/ttrss-docker-compose/wiki/Home#how-do-i-set-global-configuration-options)
Then restart the container. A new config was generated. 
The webpage showed a SQL connection exception.
The DB port in the config was missing in my config. Even when setting it as docker env variable.
Set it manual in the config file.
Everything worked fine.

Maybe this helps somebody.

**Comment by lunik1** [comment]
As other users have noted this is due to an upstream change in the configuration format for `tt-rss`. More info including how to migrate from an existing `config.php` can be found [here](https://git.tt-rss.org/fox/tt-rss/wiki/GlobalConfig), but the TLDR is change your
```php
define('OPTION', 'value');
```
to
```php
putenv('TTRSS_OPTION=value')
```

I'm having even more trouble than @Biepa when it comes to environment variables, though. Tt-rss isn't picking up any of them. I would advise using `config.php` for now, I will close this issue once there is a fix for environment variables.

**Comment by RealOrangeOne** [comment]
I too have had issues with TT-RSS picking up environment variable changes. if I use `putenv` _inside_ the `config.php`, it works absolutely fine. Defining the same variables through Docker's `environment` key doesn't work. I'm guessing somehow the defined variables are being stripped out.

**Comment by lunik1** [comment]
If I run bash as the `abc` user and look for them they're there.

A possible workaround is to alter the logic in `/etc/cont-init.d/30-config` to generate a `config.php` with `putenv` statements, but it's a bit hacky.

**Comment by lunik1** [comment]
This _should_ be fixed as of 567ed17. If you use `config.ini` you will need to make the changes described earlier in this thread (it's a breaking change upstream so I think it's reasonable for it to a breaking change here too). Using environment variables should work again without any required changes.

The environment variables tt-rss now uses upstream are prefixed with `TTRSS_`, i.e. `TTRSS_DB_TYPE` vs this container's `DB_TYPE`. Both should now work with this container but the former style should be considered deprecated. It may be removed without warning (but I'm not planning it) and an equivalent will not be introduced for any new/changed configuration variables upstream.

**Comment by lunik1** [comment]
@Dinth @RealOrangeOne still experiencing any issues?

**Comment by RealOrangeOne** [comment]
I actually just caved and put the environment variables in a `config.php` as the documentation said. I'll try using Docker environment variables now

**Comment by RealOrangeOne** [comment]
@lunik1 Yup, that appears to be working perfectly now :tada: 

Changes and working config can be seen at https://github.com/RealOrangeOne/infrastructure/commit/3eb286c9bd9143a70435ba5d30ebab99a465a5b3
