### ISSUE TITLE
Startup failure after 26 Feb update

### ISSUE THREAD

**Issue by tedall** [lunik1/docker-tt-rss#4]
The container was updated last night by watchtower without any issues. Startup also produced no errors in the log. However, accessing tt-rss failed with incorrect self_url, although the config.php has not been changed at all.

![image](https://user-images.githubusercontent.com/45913113/109277612-da7ae480-7817-11eb-8c78-c7a496f2ac73.png)

Apparently some of the [latest changes](https://community.tt-rss.org/t/rip-config-php-hello-classes-config-php/4337) to tt-rss are not yet reflected in this image. I have set up a new container from scratch with an new config directory and the new structure of tt-rss io not reflected there (i.e. no config.php exists either in root or the classes subdir)

**Comment by rosti76** [comment]
You have to migrate your config.php to new format, no migration tool available from TT-rss.

https://community.tt-rss.org/t/rip-config-php-hello-classes-config-php/4337

**Comment by lunik1** [comment]
Thanks for the info, further discussion should take place in #3
