### ISSUE TITLE
URL Path issues after latest update

### ISSUE THREAD

**Issue by bptillman** [lunik1/docker-tt-rss#7]
After the latest update pulled from dockerhub and the schema was migrated, now I was getting an error when loading the app. 
The first error seen was:

> E_URL_SCHEME_MISMATCH
> URL scheme reported by your browser (https) doesn't match server-configured SELF_URL_PATH (http), check X-Forwarded-Proto.
> Additional information:
> SELF_URL_PATH: http://tinyrss.mydomainhere.com
> CLIENT_LOCATION: https://tinyrss.mydomainhere.com/

I go to https://tinyrss.mydomainhere.com to hit my ttrss instance behind a reverse proxy, so the error made sense to me since http was specific in my config.php. So from seeing that error I changed the config.php from:
`putenv('TTRSS_SELF_URL_PATH=http://tinyrss.mydomainhere.com/');`
to
`putenv('TTRSS_SELF_URL_PATH=https://tinyrss.mydomainhere.com/');`

After doing that and restarting the container, now when I visit https://tinyrss.mydomainhere.com , instead of the fatal error I am seeing:

> Startup failed
> 
> Please fix errors indicated by the following messages:
> Please set SELF_URL_PATH to the correct value detected for your server: http://tinyrss.mydomainhere.com (you're using: https://tinyrss.mydomainhere.com)

Any help or ideas of what else I should be looking for would be much appreciated.

Update:
I also have tried renaming the existing config.php and replacing all of the needed config values with docker environment variables that all start with TTRSS_ per the newest changes and am still seeing the "startup failed" message from directly above. So I'm not sure what other configuration issue it could be causing this.

**Comment by lbouriez** [comment]
Hello @bptillman 
Did you try using the env variable instead of the config.php ?
Do you have a repo so I can test ?

**Comment by bptillman** [comment]
> 
> 
> Hello @bptillman
> Did you try using the env variable instead of the config.php ?
> Do you have a repo so I can test ?

I was finally able to test with the newer version utilizing env vars and it looks to be working. 👍
